# Generated by Django 5.2.16 on 2026-07-28 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50, unique=True)),
                ('rank', models.CharField(choices=[('NOVATO', 'Novato'), ('VANGUARD', 'Vanguard'), ('ALPHA', 'Alpha'), ('ELITE', 'Elite'), ('LEGEND', 'Legend')], default='NOVATO', max_length=20)),
                ('level', models.PositiveIntegerField(default=1)),
                ('xp_total', models.PositiveIntegerField(default=0)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('current_weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operator Profile',
                'verbose_name_plural': 'Operator Profiles',
            },
        ),
    ]
