# Generated by Django 5.2.16 on 2026-07-28 16:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stimulus_type', models.CharField(choices=[('FUERZA_MAX', 'Fuerza Máxima'), ('HIPERTROFIA', 'Hipertrofia'), ('RESISTENCIA', 'Resistencia'), ('POTENCIA', 'Potencia'), ('RESISTENCIA_MUSCULAR', 'Resistencia Muscular')], max_length=30)),
                ('status', models.CharField(choices=[('ALPHA', 'Alpha'), ('STABLE', 'Stable'), ('BETA', 'Beta')], default='BETA', max_length=10)),
                ('estimated_duration_min', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)])),
                ('metabolic_load_kcal', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='accounts.operatorprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('muscle_group', models.CharField(choices=[('PUSH', 'Push'), ('PULL', 'Pull'), ('CORE', 'Core'), ('LEGS', 'Legs'), ('FULL_BODY', 'Full Body')], max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('sets', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('reps', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('target_weight_kg', models.DecimalField(decimal_places=1, max_digits=6)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='protocols.protocol')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('protocol', 'order')},
            },
        ),
    ]
