# Generated by Django 5.2.16 on 2026-07-28 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('actual_duration_min', models.PositiveIntegerField()),
                ('total_load_kg', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('estimated_calories', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('notes', models.TextField(blank=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='accounts.operatorprofile')),
                ('protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='protocols.protocol')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
