# Generated by Django 5.2.16 on 2026-07-28 16:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroupVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle_group', models.CharField(choices=[('PUSH', 'Push'), ('PULL', 'Pull'), ('CORE', 'Core'), ('LEGS', 'Legs'), ('FULL_BODY', 'Full Body')], max_length=20)),
                ('volume_kg', models.DecimalField(decimal_places=1, max_digits=8)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_by_group', to='training.trainingsession')),
            ],
            options={
                'verbose_name_plural': 'Muscle group volumes',
                'unique_together': {('session', 'muscle_group')},
            },
        ),
        migrations.CreateModel(
            name='ProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)])),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('measurements', models.JSONField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='accounts.operatorprofile')),
            ],
            options={
                'verbose_name_plural': 'Progress entries',
                'ordering': ['-date'],
                'unique_together': {('operator', 'date')},
            },
        ),
    ]
