# Generated by Django 5.2.16 on 2026-07-28 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('ALTO', 'Alto'), ('MEDIO', 'Medio'), ('BAJO', 'Bajo')], default='MEDIO', max_length=10)),
                ('mission_type', models.CharField(choices=[('EJERCICIO', 'Ejercicio'), ('HIDRATACION', 'Hidratación'), ('SUENO', 'Sueño'), ('CUSTOM', 'Custom')], default='EJERCICIO', max_length=20)),
                ('xp_reward', models.PositiveIntegerField(default=10)),
                ('current_progress', models.PositiveIntegerField(default=0)),
                ('goal', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='accounts.operatorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
